from io import BytesIO
from docx import Document


def add_bullet_list(doc, items):
    if not items:
        doc.add_paragraph("No data available.")
        return

    for item in items:
        doc.add_paragraph(str(item), style="List Bullet")


def generate_docx_report(analysis_data, theory_support):
    doc = Document()

    doc.add_heading("AI UX Research Report", level=0)
    doc.add_paragraph(
        "This report was generated by an AI-assisted UX Research Agent. "
        "Please review and refine the content before final use."
    )

    overview = analysis_data.get("project_overview", {})
    directions = analysis_data.get("design_directions", {})

    doc.add_heading("1. Executive Summary", level=1)
    doc.add_paragraph(f"Research Context: {overview.get('research_context', '')}")
    doc.add_paragraph(f"Main User Group: {overview.get('main_user_group', '')}")
    doc.add_paragraph(f"Core Problem: {overview.get('core_problem', '')}")
    doc.add_paragraph(f"Problem Statement: {directions.get('problem_statement', '')}")
    doc.add_paragraph(f"Final Direction Summary: {directions.get('final_direction_summary', '')}")

    limitations = overview.get("research_limitations", "")
    if limitations:
        doc.add_heading("Research Limitations", level=2)
        doc.add_paragraph(limitations)

    doc.add_heading("2. UX Insights", level=1)
    ux_insights = analysis_data.get("ux_insights", {})

    doc.add_heading("Pain Points", level=2)
    for item in ux_insights.get("pain_points", []):
        doc.add_heading(item.get("title", "Untitled Pain Point"), level=3)
        doc.add_paragraph(f"What happens: {item.get('what_happens', '')}")
        doc.add_paragraph(f"Why it matters: {item.get('why_it_matters', '')}")
        doc.add_paragraph(f"Design implication: {item.get('design_implication', '')}")
        doc.add_paragraph(f"Evidence: {item.get('supporting_quote_or_evidence', '')}")

    doc.add_heading("Behavioral Patterns", level=2)
    for item in ux_insights.get("behavioral_patterns", []):
        doc.add_heading(item.get("title", "Untitled Behavioral Pattern"), level=3)
        doc.add_paragraph(f"Observed behavior: {item.get('observed_behavior', '')}")
        doc.add_paragraph(f"Interpretation: {item.get('interpretation', '')}")
        doc.add_paragraph(f"Design implication: {item.get('design_implication', '')}")
        doc.add_paragraph(f"Evidence: {item.get('supporting_quote_or_evidence', '')}")

    doc.add_heading("Emotional Needs", level=2)
    for item in ux_insights.get("emotional_needs", []):
        doc.add_heading(item.get("title", "Untitled Emotional Need"), level=3)
        doc.add_paragraph(f"Emotional signal: {item.get('emotional_signal', '')}")
        doc.add_paragraph(f"Underlying need: {item.get('underlying_need', '')}")
        doc.add_paragraph(f"Design implication: {item.get('design_implication', '')}")
        doc.add_paragraph(f"Evidence: {item.get('supporting_quote_or_evidence', '')}")

    doc.add_heading("3. Affinity Map", level=1)
    for group in analysis_data.get("affinity_map", []):
        doc.add_heading(group.get("theme", "Untitled Theme"), level=2)
        doc.add_paragraph(f"Theme summary: {group.get('theme_summary', '')}")
        doc.add_paragraph("Key Insights:")
        add_bullet_list(doc, group.get("insights", []))
        doc.add_paragraph("Supporting Evidence:")
        add_bullet_list(doc, group.get("evidence", []))
        doc.add_paragraph(f"Design opportunity: {group.get('design_opportunity', '')}")

    doc.add_heading("4. User Persona", level=1)
    persona = analysis_data.get("user_persona", {})
    doc.add_paragraph(f"Name: {persona.get('name', '')}")
    doc.add_paragraph(f"Role: {persona.get('role', '')}")
    doc.add_paragraph(f"Background: {persona.get('background', '')}")
    doc.add_paragraph(f"Primary Goal: {persona.get('primary_goal', '')}")
    doc.add_paragraph(f"Quote: {persona.get('quote', '')}")

    doc.add_heading("Goals", level=2)
    add_bullet_list(doc, persona.get("goals", []))

    doc.add_heading("Frustrations", level=2)
    add_bullet_list(doc, persona.get("frustrations", []))

    doc.add_heading("Behaviors", level=2)
    add_bullet_list(doc, persona.get("behaviors", []))

    doc.add_heading("Needs", level=2)
    add_bullet_list(doc, persona.get("needs", []))

    doc.add_heading("Trust Barriers", level=2)
    add_bullet_list(doc, persona.get("trust_barriers", []))

    doc.add_heading("5. User Journey Map", level=1)
    journey = analysis_data.get("user_journey_map", [])

    if journey:
        table = doc.add_table(rows=1, cols=8)
        table.style = "Table Grid"

        headers = [
            "Stage",
            "User Goal",
            "User Actions",
            "Thoughts",
            "Emotions",
            "Pain Points",
            "Opportunities",
            "Possible Feature Response"
        ]

        for i, header in enumerate(headers):
            table.rows[0].cells[i].text = header

        for row in journey:
            cells = table.add_row().cells
            cells[0].text = row.get("stage", "")
            cells[1].text = row.get("user_goal", "")
            cells[2].text = row.get("user_actions", "")
            cells[3].text = row.get("thoughts", "")
            cells[4].text = row.get("emotions", "")
            cells[5].text = row.get("pain_points", "")
            cells[6].text = row.get("opportunities", "")
            cells[7].text = row.get("possible_feature_response", "")

    doc.add_heading("6. Service Blueprint", level=1)
    blueprint = analysis_data.get("service_blueprint", [])

    if blueprint:
        table = doc.add_table(rows=1, cols=8)
        table.style = "Table Grid"

        headers = [
            "Stage",
            "User Actions",
            "Frontstage Touchpoints",
            "Backstage Processes",
            "Support Systems",
            "Pain Points",
            "Opportunities",
            "Design Requirement"
        ]

        for i, header in enumerate(headers):
            table.rows[0].cells[i].text = header

        for row in blueprint:
            cells = table.add_row().cells
            cells[0].text = row.get("stage", "")
            cells[1].text = row.get("user_actions", "")
            cells[2].text = row.get("frontstage_touchpoints", "")
            cells[3].text = row.get("backstage_processes", "")
            cells[4].text = row.get("support_systems", "")
            cells[5].text = row.get("pain_points", "")
            cells[6].text = row.get("opportunities", "")
            cells[7].text = row.get("design_requirement", "")

    doc.add_heading("7. Theory Support", level=1)
    doc.add_paragraph(theory_support)

    doc.add_heading("8. Design Directions", level=1)

    doc.add_heading("Problem Statement", level=2)
    doc.add_paragraph(directions.get("problem_statement", ""))

    doc.add_heading("Design Principles", level=2)
    add_bullet_list(doc, directions.get("design_principles", []))

    doc.add_heading("Opportunity Areas", level=2)
    for area in directions.get("opportunity_areas", []):
        doc.add_heading(area.get("title", "Untitled Opportunity"), level=3)
        doc.add_paragraph(f"Description: {area.get('description', '')}")
        doc.add_paragraph(f"Why it matters: {area.get('why_it_matters', '')}")

    doc.add_heading("Recommended Features", level=2)
    for feature in directions.get("recommended_features", []):
        doc.add_heading(feature.get("feature", "Untitled Feature"), level=3)
        doc.add_paragraph(f"User problem addressed: {feature.get('user_problem_addressed', '')}")
        doc.add_paragraph(f"Reason: {feature.get('reason', '')}")
        doc.add_paragraph(f"Priority: {feature.get('priority', '')}")

    doc.add_heading("Final Direction Summary", level=2)
    doc.add_paragraph(directions.get("final_direction_summary", ""))

    doc.add_heading("Next Research Questions", level=2)
    add_bullet_list(doc, directions.get("next_research_questions", []))

    file_stream = BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)

    return file_stream